class AlreadyExistException(Exception):
    pass

class NotExistException(Exception):
    pass
